services:
  dexi-dev:
    image: droneblocks/dexi-px4-sitl-arm64:1.15
    container_name: dexi-dev
    ports:
      - "6080:80"
      - "9090:9090"
    security_opt:
      - seccomp=unconfined
    volumes:
      - "${PWD}/dexi:/home/ubuntu/dexi_ws/src/"
    shm_size: "512m"

  dexi-node-red:
    image: droneblocks/dexi-node-red:latest
    container_name: dexi-node-red
    ports:
      - "1880:1880"
    volumes:
      - "${PWD}/node-red-dexi/flows:/data"
    stdin_open: true
    tty: true
