services:
  dexi-dev:
    image: wravr/wr-dexi:latest
    container_name: dexi-dev
    ports:
      - "6080:80"
      - "9090:9090"
    security_opt:
      - seccomp=unconfined
    volumes:
      - "./dexi:/var/lib/docker"
    shm_size: "512m"
